/**
 * PlanViewerProvider — Webview for Plan Display
 *
 * Renders the structured plan generated by the Workflow planner.
 * Provides big ✅ Approve and ❌ Reject buttons to gate execution.
 */

import * as vscode from 'vscode';
import { Plan, WorkflowPhase, WorkflowState } from '../core/workflow/types';
import { WorkflowLoop } from '../core/workflow/loop';

export class PlanViewerProvider implements vscode.WebviewViewProvider {
  private view?: vscode.WebviewView;

  constructor(
    private readonly extensionUri: vscode.Uri,
    private readonly workflowLoop: WorkflowLoop
  ) {
    this.workflowLoop.onPhaseChange((state) => {
      this.updateView(state);
    });
  }

  public resolveWebviewView(
    webviewView: vscode.WebviewView,
    _context: vscode.WebviewViewResolveContext,
    _token: vscode.CancellationToken
  ): void {
    this.view = webviewView;
    webviewView.webview.options = {
      enableScripts: true,
      localResourceRoots: [this.extensionUri],
    };

    // Initialize with current state
    this.updateView({ phase: this.workflowLoop.phase, plan: this.workflowLoop.currentPlan });

    webviewView.webview.onDidReceiveMessage((msg) => {
      switch (msg.command) {
        case 'approve':
          vscode.commands.executeCommand('echocoder.approvePlan');
          break;
        case 'reject':
          vscode.commands.executeCommand('echocoder.rejectPlan');
          break;
      }
    });
  }

  /**
   * Show the Plan Viewer panel and ensure it's visible.
   */
  public show(): void {
    vscode.commands.executeCommand('echocoder.planViewer.focus');
  }

  private updateView(state: WorkflowState): void {
    if (!this.view) { return; }

    const { phase, plan } = state;
    this.view.webview.html = this.getHtml(phase, plan);

    if (phase === 'awaiting_approval' && plan) {
      // Auto-show when plan is ready for approval
      this.show();
    }
  }

  private getHtml(phase: WorkflowPhase, plan?: Plan): string {
    const styleUri = this.getStyleUri();
    
    if (!plan || phase === 'idle' || phase === 'planning') {
      const message = phase === 'planning' 
        ? '<div class="state-msg">Generating plan... <span class="spinner"></span></div>' 
        : '<div class="state-msg">No active plan</div>';
        
      return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>${styleUri}</style>
</head>
<body>
  <div class="empty-state">${message}</div>
</body>
</html>`;
    }

    const { summary, risk, steps, readFiles, writeFiles } = plan;
    const isAwaitingApproval = phase === 'awaiting_approval';
    const isExecuting = phase === 'executing';
    const isCompleted = phase === 'completed';
    const isFailed = phase === 'failed';

    // Risk badge color
    const riskColor = risk === 'low' ? 'var(--vscode-charts-green)' : 
                     risk === 'medium' ? 'var(--vscode-charts-yellow)' : 
                     'var(--vscode-charts-red)';

    const stepsHtml = steps.map(s => {
      const statusIcon = 
        s.status === 'pending' ? '⏳' :
        s.status === 'running' ? '🔄' :
        s.status === 'done' ? '✅' :
        s.status === 'failed' ? '❌' : '⏭️';
        
      const statusClass = s.status === 'running' ? 'step-running' : '';
        
      return `
      <div class="plan-step ${statusClass}">
        <div class="step-header">
          <span class="step-index">${s.index}.</span>
          <span class="step-category badge-${s.category}">${s.category}</span>
          <span class="step-status">${statusIcon}</span>
        </div>
        <div class="step-desc">${this.escapeHtml(s.description)}</div>
        ${s.affectedFiles.length > 0 ? `<div class="step-files">Files: ${s.affectedFiles.join(', ')}</div>` : ''}
        ${s.output ? `<div class="step-error">${this.escapeHtml(s.output)}</div>` : ''}
      </div>`;
    }).join('');

    const filesHtml = `
      <div class="files-summary">
        <div><strong>Writes to:</strong> ${writeFiles.length > 0 ? writeFiles.join(', ') : 'None'}</div>
        <div><strong>Reads from:</strong> ${readFiles.length > 0 ? readFiles.join(', ') : 'None'}</div>
      </div>
    `;

    const actionsHtml = isAwaitingApproval ? `
      <div class="actions fixed-bottom">
        <button class="button-primary" id="btn-approve">Approve & Execute</button>
        <button class="button-secondary" id="btn-reject">Reject Plan</button>
      </div>` : '';

    const headerStatus = 
      isExecuting ? '<span style="color: var(--vscode-charts-blue)">Executing...</span>' :
      isCompleted ? '<span style="color: var(--vscode-charts-green)">Completed</span>' :
      isFailed ? '<span style="color: var(--vscode-charts-red)">Failed</span>' :
      '<span style="color: var(--vscode-charts-yellow)">Awaiting Approval</span>';

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>${styleUri}</style>
</head>
<body>
  <div class="plan-container ${isAwaitingApproval ? 'has-actions' : ''}">
    <div class="plan-header">
      <h2>Plan Overview</h2>
      <div class="meta-row">
        <span class="badge" style="background-color: ${riskColor}; color: #000">Risk: ${risk}</span>
        <span class="status-indicator">${headerStatus}</span>
      </div>
    </div>
    
    <div class="plan-summary">
      ${this.escapeHtml(summary)}
    </div>

    ${filesHtml}

    <div class="steps-container">
      <h3>Execution Steps</h3>
      ${stepsHtml}
    </div>
  </div>

  ${actionsHtml}

  <script>
    const vscode = acquireVsCodeApi();
    
    document.getElementById('btn-approve')?.addEventListener('click', () => {
      vscode.postMessage({ command: 'approve' });
    });
    
    document.getElementById('btn-reject')?.addEventListener('click', () => {
      vscode.postMessage({ command: 'reject' });
    });
  </script>
</body>
</html>`;
  }

  /**
   * Escape HTML to prevent injection
   */
  private escapeHtml(unsafe: string): string {
    return unsafe
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;")
      .replace(/'/g, "&#039;");
  }

  private getStyleUri(): string {
    // Inline CSS for the webview to keep it self-contained
    return `
      body {
        font-family: var(--vscode-font-family);
        color: var(--vscode-editor-foreground);
        padding: 0;
        margin: 0;
      }
      
      .empty-state {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        color: var(--vscode-descriptionForeground);
      }
      
      .plan-container {
        padding: 10px;
        padding-bottom: 20px;
      }
      
      .has-actions {
        padding-bottom: 60px; /* Space for fixed bottom buttons */
      }
      
      .plan-header {
        margin-bottom: 15px;
        border-bottom: 1px solid var(--vscode-panel-border);
        padding-bottom: 10px;
      }
      
      .plan-header h2 {
        margin: 0 0 5px 0;
        font-size: 14px;
        font-weight: 600;
      }
      
      .meta-row {
        display: flex;
        justify-content: space-between;
        align-items: center;
        font-size: 11px;
      }
      
      .badge {
        padding: 2px 6px;
        border-radius: 3px;
        font-weight: bold;
      }
      
      .plan-summary {
        font-size: 13px;
        margin-bottom: 15px;
        line-height: 1.4;
      }
      
      .files-summary {
        font-size: 11px;
        padding: 8px;
        background-color: var(--vscode-textBlockQuote-background);
        border-left: 3px solid var(--vscode-textBlockQuote-border);
        margin-bottom: 15px;
        word-break: break-all;
      }
      
      .steps-container h3 {
        font-size: 12px;
        text-transform: uppercase;
        margin-bottom: 10px;
        color: var(--vscode-descriptionForeground);
      }
      
      .plan-step {
        margin-bottom: 12px;
        padding: 8px;
        border: 1px solid var(--vscode-panel-border);
        border-radius: 4px;
        background-color: var(--vscode-editor-background);
      }
      
      .step-running {
        border-color: var(--vscode-focusBorder);
        box-shadow: 0 0 3px var(--vscode-focusBorder);
      }
      
      .step-header {
        display: flex;
        align-items: center;
        margin-bottom: 5px;
      }
      
      .step-index {
        font-weight: bold;
        margin-right: 5px;
      }
      
      .step-category {
        font-size: 10px;
        padding: 1px 4px;
        border-radius: 2px;
        background-color: var(--vscode-badge-background);
        color: var(--vscode-badge-foreground);
        margin-right: auto;
      }
      
      .step-desc {
        font-size: 12px;
        margin-bottom: 4px;
      }
      
      .step-files {
        font-size: 10px;
        color: var(--vscode-textPreformat-foreground);
        word-break: break-all;
      }
      
      .step-error {
        margin-top: 5px;
        font-size: 11px;
        color: var(--vscode-errorForeground);
        background-color: rgba(255, 0, 0, 0.1);
        padding: 4px;
        border-radius: 2px;
      }
      
      .fixed-bottom {
        position: fixed;
        bottom: 0;
        left: 0;
        right: 0;
        padding: 10px;
        background-color: var(--vscode-editor-background);
        border-top: 1px solid var(--vscode-panel-border);
        display: flex;
        gap: 10px;
      }
      
      button {
        flex: 1;
        padding: 6px;
        cursor: pointer;
        border-radius: 2px;
        border: none;
        font-weight: bold;
      }
      
      .button-primary {
        background-color: var(--vscode-button-background);
        color: var(--vscode-button-foreground);
      }
      
      .button-primary:hover {
        background-color: var(--vscode-button-hoverBackground);
      }
      
      .button-secondary {
        background-color: var(--vscode-button-secondaryBackground);
        color: var(--vscode-button-secondaryForeground);
      }
      
      .button-secondary:hover {
        background-color: var(--vscode-button-secondaryHoverBackground);
      }
    `;
  }
}
