import * as fs from 'fs';
import { execSync } from 'child_process';

/**
 * Doc-Sync Agent (The Scribe)
 * 
 * Analyzes PR diffs to ensure code changes are documented.
 * Can autonomously generate draft documentation commits.
 */
async function runDocSync() {
  const prNumber = process.env.PR_NUMBER;
  if (!prNumber) {
    console.warn('⚠️ No PR_NUMBER. Skipping doc-sync.');
    process.exit(0);
  }

  console.log(`✍️ Scribe: Analyzing PR #${prNumber} for documentation parity...`);

  // 1. Get changed files
  const changedFiles = execSync('git diff --name-only origin/main...HEAD', { encoding: 'utf8' })
    .split('\n')
    .filter(f => f.trim().length > 0);

  const codeChanges = changedFiles.filter(f => f.startsWith('src/') && (f.endsWith('.ts') || f.endsWith('.js')));
  const docChanges = changedFiles.filter(f => f.startsWith('docs/'));

  if (codeChanges.length > 0 && docChanges.length === 0) {
    console.log('🧐 Diagnosis: Code changed in src/ but no updates in docs/. Potential documentation drift.');
    
    // Check if new "public" exports were added
    const diff = execSync('git diff origin/main...HEAD src/', { encoding: 'utf8' });
    const hasNewExports = diff.includes('+export ') || diff.includes('+export default');

    if (hasNewExports) {
      console.log('📄 Found new exports without documentation. Generating draft docs...');
      const draftDoc = `
# New Feature Documentation (Draft)

*Autogenerated by EchoCoder Scribe Agent*

Based on the recent changes in PR #${prNumber}, the following areas were updated:
${codeChanges.map(f => `- ${f}`).join('\n')}

**Please review and finalize this documentation update.**
`;
      const draftPath = `docs/updates/pr-${prNumber}-draft.md`;
      fs.mkdirSync('docs/updates', { recursive: true });
      fs.writeFileSync(draftPath, draftDoc);

      console.log(`✅ Draft documentation created at ${draftPath}`);

      if (process.env.CI) {
        execSync('git config --global user.name "EchoCoder Scribe"');
        execSync('git config --global user.email "scribe@echocoder.ai"');
        execSync(`git add ${draftPath}`);
        execSync(`git commit -m "docs(scribe): auto-draft documentation for PR #${prNumber}"`);
        
        const headRef = process.env.GITHUB_HEAD_REF;
        if (headRef) {
          execSync(`git push origin HEAD:${headRef}`, { stdio: 'inherit' });
          console.log('✅ Autonomous documentation draft pushed.');
        }
      }
    }
  } else {
    console.log('✅ Documentation parity check passed.');
  }
}

runDocSync().catch(console.error);
