/**
 * Workflow Engine Types
 *
 * Shared interfaces for the Plan → Approve → Execute → Verify loop.
 * These types form the contract between planner, executor, verifier,
 * plan viewer UI, and the orchestration loop.
 */

/**
 * A single step within a plan.
 */
export interface PlanStep {
  /** Sequential index (1-based). */
  index: number;

  /** Human-readable description of what this step does. */
  description: string;

  /** Tool category this step will likely invoke. */
  category: 'read' | 'write' | 'create' | 'delete' | 'execute' | 'refactor' | 'test' | 'other';

  /** Files this step will touch (if known). */
  affectedFiles: string[];

  /** Risk level for display in the UI. */
  risk: 'low' | 'medium' | 'high';

  /** Current execution status, updated by the executor. */
  status: 'pending' | 'running' | 'done' | 'failed' | 'skipped';

  /** Optional output or error message produced during execution. */
  output?: string;

  /** Pre-mutation content for diff preview. */
  oldContent?: string;

  /** Post-mutation content for diff preview. */
  newContent?: string;
}

/**
 * The structured plan produced by the planner phase.
 */
export interface Plan {
  /** Unique identifier for this plan. */
  id: string;

  /** The original user prompt that triggered this plan. */
  userPrompt: string;

  /** One-line summary generated by the agent. */
  summary: string;

  /** Ordered list of steps the agent intends to execute. */
  steps: PlanStep[];

  /** All files the plan will read from. */
  readFiles: string[];

  /** All files the plan will modify or create. */
  writeFiles: string[];

  /** Overall risk assessment. */
  risk: 'low' | 'medium' | 'high';

  /** Raw markdown text produced by the agent (for fallback rendering). */
  rawMarkdown: string;

  /** Lifecycle state of this plan. */
  state: 'draft' | 'approved' | 'rejected' | 'executing' | 'completed' | 'failed';

  /** Timestamp when the plan was generated. */
  createdAt: number;
}

/**
 * Result of executing an approved plan.
 */
export interface ExecutionResult {
  /** The plan that was executed. */
  planId: string;

  /** Whether execution completed without agent errors. */
  success: boolean;

  /** Steps with their final statuses. */
  steps: PlanStep[];

  /** Files actually modified during execution. */
  modifiedFiles: string[];

  /** Files created during execution. */
  createdFiles: string[];

  /** Any agent error message. */
  error?: string;

  /** Duration in milliseconds. */
  durationMs: number;
}

/**
 * A single check within the verification phase.
 */
export interface VerificationCheck {
  name: string;
  command: string;
  passed: boolean;
  output: string;
  durationMs: number;
}

/**
 * Report produced by the verifier after execution.
 */
export interface VerificationReport {
  /** The plan that was verified. */
  planId: string;

  /** Overall pass/fail. */
  passed: boolean;

  /** Individual check results. */
  checks: VerificationCheck[];

  /** Summary message. */
  summary: string;
}

/**
 * Lifecycle events emitted by the workflow loop.
 */
export type WorkflowPhase =
  | 'idle'
  | 'planning'
  | 'repairing'
  | 'awaiting_approval'
  | 'executing'
  | 'verifying'
  | 'completed'
  | 'failed';

export interface WorkflowState {
  phase: WorkflowPhase;
  plan?: Plan;
  executionResult?: ExecutionResult;
  verificationReport?: VerificationReport;
}
